### ISSUE TITLE
Analyse possible improvement for cronjob termination

### ISSUE THREAD

**Issue by rbock44** [serlo/stats.serlo.org#68] opened 2019-06-20 21:06 UTC
Currently running database transactions should not be terminated. Usually the jobs do not run really long.

Can we catch the SIG_TERM and stop cronjob and terminate after a configurable time?

Is that not necessary?

**Comment by rbock44** [comment] 2019-06-20 21:07
Just some food for thoughts to make the cron jobs more stable avoiding any corruption. Or am I paranoid?

**Comment by Lodifice** [comment] 2019-06-21 06:22
Just to be clear: are you only talking about terminating from command line, i.e., if I do a docker-run and then press Ctrl+C?
Then I don't find it necessary, because the output on the command line tells me when it's done. Of course, we could just replace the `trap "kill $!"` by `trap "sleep 1 && kill $!"` or wait until all the `psql` processes are done.

**Comment by rbock44** [comment] 2019-06-21 07:04
No I ment the kubernetes one running in gcloud. In minikube we also can delete the cluster and repeat. But kubernetes will also shutdown our container and we can add some grace time where it will wait until it really terminates the container. In the meantime we should already terminate the crond to avoid starrting a new one and just hope that the time is sufficient for the current transaction.

But I thought we atleast already should terminate the crond and then do a short sleep and terminate.
What do you think?

**Comment by vroland** [comment] 2019-07-17 18:15
For the aggregator (and importer?), since we use Database Transactions, which should be ACID by design, we should be fine with just terminating. Postgres on the other hand should be given enough time to shut down...

**Comment by kulla** [comment] 2020-06-17 17:47
Shouldn't be an issue when we implement https://github.com/serlo/stats.serlo.org/issues/132 -> I close this issue

**Closed by kulla** 2020-06-17 17:47 UTC
